SELECT
	b.CUS_NO
	,b.[YEAR]
	,b.[MONTH]
	,b.DURATION
	,b.AMTN_OUT
	,CASE
		WHEN c.G_PERIOD<=b.DURATION THEN 0
		ELSE c.G_PERIOD-b.DURATION
	END AS G_PERIOD_REMAIN
	,CASE
		WHEN b.DURATION<c.G_PERIOD THEN 0
		ELSE 1
	END AS [STATUS]
	,CASE
		WHEN c.G_PERIOD<=b.DURATION THEN DATEDIFF(mm,DATEADD(DAY,-b.DURATION,GETDATE()),GETDATE())+1
		ELSE 0
	END AS LATE_COUNT
FROM (
	SELECT
		a.CUS_NO
		,YEAR(a.PS_DD) AS [YEAR]
		,MONTH(a.PS_DD) AS [MONTH]
		,SUM(DATEDIFF(dd,a.PS_DD,GETDATE()))/COUNT(*) AS DURATION
		,SUM(a.AMTN_OUT) AS AMTN_OUT
	FROM sunlikeerp.overdueMonitor.dbo.outstanding a
	GROUP BY a.CUS_NO,YEAR(a.PS_DD),MONTH(a.PS_DD)) b
	LEFT JOIN sunlikeerp.overdueMonitor.dbo.paymentTerm c ON b.CUS_NO=c.CUS_NO;

/* 未完成
SELECT
	a.CUS_NO
	,a.[YEAR]
	,a.[MONTH]
	,SUM(a.DURATION)/COUNT(*) AS DURATION
	,SUM(a.AMTN_OUT) AS AMTN_OUT
	,SUM(a.G_PERIOD_REMAIN)/COUNT(*) AS G_PERIOD_REMAIN
	,a.[STATUS]
	,SUM(a.G_PERIOD-a.DURATION)/COUNT(*)
	,CASE WHEN a.[STATUS]=1 THEN 
	ELSE 0 END AS LATE_COUNT
FROM sunlikeerp.overdueMonitor.dbo.outstanding a
GROUP BY a.CUS_NO,a.[YEAR],a.[MONTH],a.[STATUS];
*/