SELECT
	a.CUS_NO
	,b.SAL_NO
	,b.CUS_SNM
	,a.AMTN_OVERDUE
	,b.SAL_NAME
FROM (
	SELECT TOP 10
		CUS_NO
		,SUM(AMTN_OVERDUE) AS AMTN_OVERDUE
		,[STATUS]
	FROM UPGI_OverdueMonitor.dbo.overdue
	GROUP BY CUS_NO,[STATUS]
	ORDER BY SUM(AMTN_OVERDUE) DESC) a
	INNER JOIN UPGI_OverdueMonitor.dbo.clientData b ON a.CUS_NO=(b.CUS_NO COLLATE Compatibility_196_404_30001)
ORDER BY a.AMTN_OVERDUE DESC;